CREATE DATABASE IF NOT EXISTS LEARNLOOP_ANALYTICS;

CREATE SCHEMA IF NOT EXISTS LEARNLOOP_ANALYTICS.RAW;

USE DATABASE LEARNLOOP_ANALYTICS;
USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT JSON_FORMAT
    TYPE = JSON;

CREATE OR REPLACE STAGE LEARNLOOP_S3_STAGE
    URL = 's3://YOUR_BUCKET_NAME/raw/'
    FILE_FORMAT = JSON_FORMAT;

CREATE TABLE IF NOT EXISTS GA4_SESSIONS (
    RAW_DATA VARIANT,
    SOURCE_FILE VARCHAR,
    LOADED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS GOOGLE_ADS_CAMPAIGN_PERFORMANCE (
    RAW_DATA VARIANT,
    SOURCE_FILE VARCHAR,
    LOADED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS HUBSPOT_CONTACTS (
    RAW_DATA VARIANT,
    SOURCE_FILE VARCHAR,
    LOADED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS META_ADS_CAMPAIGN_PERFORMANCE (
    RAW_DATA VARIANT,
    SOURCE_FILE VARCHAR,
    LOADED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS STRIPE_PAYMENTS (
    RAW_DATA VARIANT,
    SOURCE_FILE VARCHAR,
    LOADED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS STRIPE_SUBSCRIPTIONS (
    RAW_DATA VARIANT,
    SOURCE_FILE VARCHAR,
    LOADED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS LEARNLOOP_COURSE_ENROLLMENTS (
    RAW_DATA VARIANT,
    SOURCE_FILE VARCHAR,
    LOADED_AT TIMESTAMP_NTZ
);
